
hydra:
  run:
    dir: outputs/${data.dataname}/${model.modelname}/${model.ckpt.name}/${experiment}/${run_name}
  job: 
    chdir: true


experiment: tv-${model.model.train_vit}_loss-${model.model.loss.name}_lr-${model.optimizer.lr}
run_name: ReTrack_CIR


seed: 1234
logger_level: INFO


defaults:
  - _self_
  - data: cirr #fashioniq #
  - machine: server
  - trainer: gpu
  - test: cirr-all #fashioniq  #
  - trainer/logger: csv
  - model: ReTrack
  - model/optimizer: adamw
  - model/scheduler: step
  - model/loss: hn_nce
  - model/ckpt: blip2-l-coco
  - model/loss_terms: si_ti

  - experiment: null
  - experiment2: null

paths: ${machine.paths}


val: True
evaluate:
  _target_: src.test.${model.basemodel}.utils.evaluate
